//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class advancedetails
    {
    
        /// <summary>  
        /// 主表单号  
        /// </summary>  
        public string advid { get; set; } 
    
        /// <summary>  
        /// 行号  
        /// </summary>  
        public Nullable<int> advdetid { get; set; } 
    
        /// <summary>  
        /// 预付金额  
        /// </summary>  
        public Nullable<float> advdetmoney { get; set; } 
    
        /// <summary>  
        /// 来源单别  
        /// </summary>  
        public string advdetoddtype { get; set; } 
    
        /// <summary>  
        /// 来源单号  
        /// </summary>  
        public string advdetoddid { get; set; } 
    
        /// <summary>  
        /// 摘要  
        /// </summary>  
        public string advdetdegest { get; set; } 
    
        /// <summary>  
        /// 预付余额  
        /// </summary>  
        public Nullable<float> advdetbalance { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> enables { get; set; } 
    }
}
