//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class advancegather
    {
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string Billid { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public System.DateTime Billdate { get; set; } 
    
        /// <summary>  
        /// 单据类型singleType(sinId)  
        /// </summary>  
        public int Sinid { get; set; } 
    
        /// <summary>  
        /// 客户编号client(cliid)  
        /// </summary>  
        public string Cliid { get; set; } 
    
        /// <summary>  
        /// 客户简称  
        /// </summary>  
        public string Clishortname { get; set; } 
    
        /// <summary>  
        /// 币别  
        /// </summary>  
        public string Currencytype { get; set; } 
    
        /// <summary>  
        /// 结算方式一  
        /// </summary>  
        public string Reckontypef { get; set; } 
    
        /// <summary>  
        /// 结算方式一  
        /// </summary>  
        public string Reckontypes { get; set; } 
    
        /// <summary>  
        /// 结算方式一  
        /// </summary>  
        public string Reckontypet { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public float Reckonmoneyf { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public float Reckonmoneys { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public float Reckonmoneyt { get; set; } 
    
        /// <summary>  
        /// 折扣率  
        /// </summary>  
        public float Gatherdiscount { get; set; } 
    
        /// <summary>  
        /// 终止帐月  
        /// </summary>  
        public System.DateTime Gatherendaccountmonth { get; set; } 
    
        /// <summary>  
        /// 业务人员编号，也就是人员编号employee(empid)  
        /// </summary>  
        public string Empid { get; set; } 
    
        /// <summary>  
        /// 业务人员  
        /// </summary>  
        public string Empname { get; set; } 
    
        /// <summary>  
        /// 部门编号depttab(depid)  
        /// </summary>  
        public string Depid { get; set; } 
    
        /// <summary>  
        /// 所属部门  
        /// </summary>  
        public string Depname { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string Makeempname { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string Auditingempname { get; set; } 
    
        /// <summary>  
        /// 审核状态  
        /// </summary>  
        public int Checkstate { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Remark { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public int Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
