//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class advance
    {
    
        /// <summary>  
        /// 预付单单号  
        /// </summary>  
        public string advid { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public Nullable<System.DateTime> advdate { get; set; } 
    
        /// <summary>  
        /// 供应商ID  
        /// </summary>  
        public string purveyid { get; set; } 
    
        /// <summary>  
        /// 供应商名称  
        /// </summary>  
        public string purveyname { get; set; } 
    
        /// <summary>  
        /// 结算方式1  
        /// </summary>  
        public string advstrike1 { get; set; } 
    
        /// <summary>  
        /// 结算方式2  
        /// </summary>  
        public string advstrike2 { get; set; } 
    
        /// <summary>  
        /// 结算方式3  
        /// </summary>  
        public string advstrike3 { get; set; } 
    
        /// <summary>  
        /// 金额1  
        /// </summary>  
        public Nullable<float> advmoney1 { get; set; } 
    
        /// <summary>  
        /// 金额2  
        /// </summary>  
        public Nullable<float> advmoney2 { get; set; } 
    
        /// <summary>  
        /// 金额3  
        /// </summary>  
        public Nullable<float> advmoney3 { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string advmakeing { get; set; } 
    
        /// <summary>  
        /// 制单人所属部门  
        /// </summary>  
        public string stodept { get; set; } 
    
        /// <summary>  
        /// 部门ID  
        /// </summary>  
        public string stodeptid { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string advcheckman { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string advremark { get; set; } 
    
        /// <summary>  
        /// 是否审核  
        /// </summary>  
        public Nullable<int> isaditing { get; set; } 
    
        /// <summary>  
        /// 保存（“预付款单”）  
        /// </summary>  
        public string safetyone { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> enables { get; set; } 
    }
}
