//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class apportiondetails
    {
    
        /// <summary>  
        /// 详表ID  
        /// </summary>  
        public string Adesequ { get; set; } 
    
        /// <summary>  
        /// 采购分摊外键  
        /// </summary>  
        public string Adeid { get; set; } 
    
        /// <summary>  
        /// 费用编号  
        /// </summary>  
        public string Adeexesid { get; set; } 
    
        /// <summary>  
        /// 费用名称  
        /// </summary>  
        public string Adeexesname { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public Nullable<float> Adeamtmoney { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
