//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class @checked
    {
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string cheid { get; set; } 
    
        /// <summary>  
        /// 盘点的仓库编号  
        /// </summary>  
        public string chestorageno { get; set; } 
    
        /// <summary>  
        /// 盘点人名称  
        /// </summary>  
        public string chejian { get; set; } 
    
        /// <summary>  
        /// 盘点的仓库名称  
        /// </summary>  
        public string chestoragename { get; set; } 
    
        /// <summary>  
        /// 盘点的日期  
        /// </summary>  
        public Nullable<System.DateTime> chedate { get; set; } 
    
        /// <summary>  
        /// 盘点人名称  
        /// </summary>  
        public string cheman { get; set; } 
    
        /// <summary>  
        /// 部门名称  
        /// </summary>  
        public string chedeptname { get; set; } 
    
        /// <summary>  
        /// 制单人-当前登录人  
        /// </summary>  
        public string cherestrictman { get; set; } 
    
        /// <summary>  
        /// 审核人-当前登录人  
        /// </summary>  
        public string cheauditingman { get; set; } 
    
        /// <summary>  
        /// 审核状态，0为未审核  
        /// </summary>  
        public Nullable<int> chestatu { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string chesone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string chestwo { get; set; } 
    
        /// <summary>  
        /// 增值科目  
        /// </summary>  
        public string chejust { get; set; } 
    
        /// <summary>  
        /// 减值科目  
        /// </summary>  
        public string cjian { get; set; } 
    }
}
