//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientaddress
    {
    
        /// <summary>  
        /// 客户地址编号  
        /// </summary>  
        public string cliaddrId { get; set; } 
    
        /// <summary>  
        /// 客户地址  
        /// </summary>  
        public string cliaddress { get; set; } 
    
        /// <summary>  
        /// 邮政编码  
        /// </summary>  
        public string clizipcode { get; set; } 
    
        /// <summary>  
        /// 联系人  
        /// </summary>  
        public string clilinkman { get; set; } 
    
        /// <summary>  
        /// 联系人职称  
        /// </summary>  
        public string clilinkmanprof { get; set; } 
    
        /// <summary>  
        /// 联系人电话  
        /// </summary>  
        public string clitelephone { get; set; } 
    
        /// <summary>  
        /// 传真号码  
        /// </summary>  
        public string clifaxno { get; set; } 
    
        /// <summary>  
        /// 行走路线  
        /// </summary>  
        public string cliwalkaddr { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string climemo { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<int> cliid { get; set; } 
    }
}
