//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
    
        /// <summary>  
        /// 客户编号  
        /// </summary>  
        public string cliId { get; set; } 
    
        /// <summary>  
        /// 客户类别Id  
        /// </summary>  
        public string clitypeid { get; set; } 
    
        /// <summary>  
        /// 客户全称  
        /// </summary>  
        public string cliName { get; set; } 
    
        /// <summary>  
        /// 客户简称  
        /// </summary>  
        public string clishortName { get; set; } 
    
        /// <summary>  
        /// 地方（具体）  
        /// </summary>  
        public string cliaddress { get; set; } 
    
        /// <summary>  
        /// 地区  
        /// </summary>  
        public string cliarea { get; set; } 
    
        /// <summary>  
        /// 英文全称  
        /// </summary>  
        public string cliename { get; set; } 
    
        /// <summary>  
        /// 英文简称  
        /// </summary>  
        public string clieshortname { get; set; } 
    
        /// <summary>  
        /// 负责人  
        /// </summary>  
        public string cliprincipal { get; set; } 
    
        /// <summary>  
        /// 联系人  
        /// </summary>  
        public string clilinkman { get; set; } 
    
        /// <summary>  
        /// 联系电话一  
        /// </summary>  
        public string cliphoneone { get; set; } 
    
        /// <summary>  
        /// 联系电话二  
        /// </summary>  
        public string cliphonetow { get; set; } 
    
        /// <summary>  
        /// 业务人员id  
        /// </summary>  
        public string empid { get; set; } 
    
        /// <summary>  
        /// 移动电话  
        /// </summary>  
        public string climobilephone { get; set; } 
    
        /// <summary>  
        /// 电子邮件  
        /// </summary>  
        public string cliemail { get; set; } 
    
        /// <summary>  
        /// 网址  
        /// </summary>  
        public string cliweb { get; set; } 
    
        /// <summary>  
        /// 传真号码  
        /// </summary>  
        public string clifaxes { get; set; } 
    
        /// <summary>  
        /// 银行帐号  
        /// </summary>  
        public string clibankaccounts { get; set; } 
    
        /// <summary>  
        /// 开户银行  
        /// </summary>  
        public string cliopenbank { get; set; } 
    }
}
