//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clienttype
    {
    
        /// <summary>  
        /// 类别编号  
        /// </summary>  
        public string Clitypeid { get; set; } 
    
        /// <summary>  
        /// 类别名称  
        /// </summary>  
        public string Clitypename { get; set; } 
    
        /// <summary>  
        /// 英文名称  
        /// </summary>  
        public string Clitypeename { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Cliremark { get; set; } 
    
        /// <summary>  
        /// 是否废码  
        /// </summary>  
        public Nullable<int> Clitypetrash { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> ENABLE { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
