//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class currencytype
    {
    
        /// <summary>  
        /// 币别编号  
        /// </summary>  
        public string CurrencyId { get; set; } 
    
        /// <summary>  
        /// 币别名称  
        /// </summary>  
        public string CurrencyName { get; set; } 
    
        /// <summary>  
        /// 币别简称  
        /// </summary>  
        public string ShorName { get; set; } 
    
        /// <summary>  
        /// 英文名称  
        /// </summary>  
        public string EngName { get; set; } 
    
        /// <summary>  
        /// 异动日期  
        /// </summary>  
        public string ModifyDate { get; set; } 
    
        /// <summary>  
        /// 固定汇率  
        /// </summary>  
        public Nullable<float> FixedRate { get; set; } 
    
        /// <summary>  
        /// 买进汇率  
        /// </summary>  
        public Nullable<float> BuyInRate { get; set; } 
    
        /// <summary>  
        /// 卖出汇率  
        /// </summary>  
        public Nullable<float> SellOutRate { get; set; } 
    
        /// <summary>  
        /// 单价位数  
        /// </summary>  
        public Nullable<float> PricedDeciDigits { get; set; } 
    
        /// <summary>  
        /// 千位逗号  
        /// </summary>  
        public Nullable<float> PriceThouPt { get; set; } 
    
        /// <summary>  
        /// 金额位数  
        /// </summary>  
        public Nullable<float> AmountDeciDi { get; set; } 
    
        /// <summary>  
        /// 千位逗号  
        /// </summary>  
        public Nullable<float> AmountThoupt { get; set; } 
    }
}
