//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class depothead
    {
    
        /// <summary>  
        ///   
        /// </summary>  
        public int id { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<int> TYPE { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string subType { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<int> customerId { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string defaultNumber { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string operPersonName { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<System.DateTime> operTime { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<System.DateTime> createTime { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string address { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string currency { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string tax { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<float> exchangeRate { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string warehouse { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string reRelease { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string foreignTrade { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string voucheId { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string invoice { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string attributionAccounts { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<System.DateTime> collectionDate { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string paymentConditions { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string accountDay { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<System.DateTime> accountMonth { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string customColumn1 { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string CustomColumn2 { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string remark { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string operationalPersonnel { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string subordinateDepartments { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string STATUS { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string reviewPersonnel { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<int> projectId { get; set; } 
    }
}
