//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class depotheaddetails
    {
    
        /// <summary>  
        ///   
        /// </summary>  
        public int depotheadId { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public int NO { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string materialNumber { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string materialName { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string specificationType { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string companyName { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<int> number { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<float> discounPric { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<float> foldingNumber { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<float> price { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<float> money { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<float> taxRate { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<float> taxAmount { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<float> taxableAmount { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string batchMumber { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string materialCombination { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string gift { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string invoiceDetails { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public Nullable<int> uninvoicedQuantity { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string notesToEntries { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string sourceList { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string sourceNo { get; set; } 
    
        /// <summary>  
        ///   
        /// </summary>  
        public string customerOrders { get; set; } 
    }
}
