//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsdaarea
    {
    
        /// <summary>  
        /// 地区编号  
        /// </summary>  
        public string AreaId { get; set; } 
    
        /// <summary>  
        /// 地区名称  
        /// </summary>  
        public string AreaName { get; set; } 
    
        /// <summary>  
        /// 英文名称  
        /// </summary>  
        public string EngName { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Memo { get; set; } 
    }
}
