//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
    
        /// <summary>  
        /// 人员编号  
        /// </summary>  
        public string Empid { get; set; } 
    
        /// <summary>  
        /// 人员姓名  
        /// </summary>  
        public string Empname { get; set; } 
    
        /// <summary>  
        /// 英文姓名  
        /// </summary>  
        public string Empename { get; set; } 
    
        /// <summary>  
        /// 部门编号id  
        /// </summary>  
        public string Depid { get; set; } 
    
        /// <summary>  
        /// 性别（默认男）  
        /// </summary>  
        public string Empsex { get; set; } 
    
        /// <summary>  
        /// 身份证号  
        /// </summary>  
        public string Empcard { get; set; } 
    
        /// <summary>  
        /// 就职状态id  
        /// </summary>  
        public string Empstate { get; set; } 
    
        /// <summary>  
        /// 职务（改字段名）  
        /// </summary>  
        public string Empduty { get; set; } 
    
        /// <summary>  
        /// 联系电话一  
        /// </summary>  
        public string Empphoneone { get; set; } 
    
        /// <summary>  
        /// 联系电话二  
        /// </summary>  
        public string Empphonetwo { get; set; } 
    
        /// <summary>  
        /// 联系电话三  
        /// </summary>  
        public string Empphonethree { get; set; } 
    
        /// <summary>  
        /// 银行账号  
        /// </summary>  
        public string Empbankaccounts { get; set; } 
    
        /// <summary>  
        /// 出生日期(修改数据类型)  
        /// </summary>  
        public Nullable<System.DateTime> Empbirthday { get; set; } 
    
        /// <summary>  
        /// 岗位  
        /// </summary>  
        public string Empjob { get; set; } 
    
        /// <summary>  
        /// 电子邮件（一个邮箱）  
        /// </summary>  
        public string Empemail { get; set; } 
    
        /// <summary>  
        /// 网址  
        /// </summary>  
        public string Empweb { get; set; } 
    
        /// <summary>  
        /// 传真号码  
        /// </summary>  
        public string Empfaxes { get; set; } 
    
        /// <summary>  
        /// 开户银行  
        /// </summary>  
        public string Empopenbank { get; set; } 
    
        /// <summary>  
        /// 最高学历  
        /// </summary>  
        public string Emptop { get; set; } 
    
        /// <summary>  
        /// 学位  
        /// </summary>  
        public string Empdegree { get; set; } 
    
        /// <summary>  
        /// 到期日期  
        /// </summary>  
        public Nullable<System.DateTime> Empgotime { get; set; } 
    
        /// <summary>  
        /// 毕业学校  
        /// </summary>  
        public string Empgraduatetime { get; set; } 
    
        /// <summary>  
        /// 合同起始日期  
        /// </summary>  
        public Nullable<System.DateTime> Emppactstarttime { get; set; } 
    
        /// <summary>  
        /// 合同终止日期  
        /// </summary>  
        public Nullable<System.DateTime> Emppactendtime { get; set; } 
    
        /// <summary>  
        /// 现邮编  
        /// </summary>  
        public string Empnowmailid { get; set; } 
    
        /// <summary>  
        /// 家庭电话  
        /// </summary>  
        public string Empfamilyphone { get; set; } 
    
        /// <summary>  
        /// 家庭住址  
        /// </summary>  
        public string Empfamilyplace { get; set; } 
    
        /// <summary>  
        /// 现电话  
        /// </summary>  
        public string Empnowphone { get; set; } 
    
        /// <summary>  
        /// 现住址  
        /// </summary>  
        public string Empnowplace { get; set; } 
    
        /// <summary>  
        /// 紧急联系人  
        /// </summary>  
        public string Empexigenceman { get; set; } 
    
        /// <summary>  
        /// 家庭邮编  
        /// </summary>  
        public string Empfamilymailid { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Empremark { get; set; } 
    
        /// <summary>  
        /// 是否废码  
        /// </summary>  
        public Nullable<int> Emptrash { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> Enables { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
