//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalledger
    {
    
        /// <summary>  
        /// 行号  
        /// </summary>  
        public string Genid { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string genmaterielid { get; set; } 
    
        /// <summary>  
        /// 仓库编号  
        /// </summary>  
        public string genstorageno { get; set; } 
    
        /// <summary>  
        /// 仓库名称  
        /// </summary>  
        public string genstoragename { get; set; } 
    
        /// <summary>  
        /// 物料类别  
        /// </summary>  
        public string genexpectstartqty { get; set; } 
    
        /// <summary>  
        /// 单位  
        /// </summary>  
        public string genstandarcost { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string gone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string gtwo { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string Genmaterielname { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string Xinghao { get; set; } 
    
        /// <summary>  
        /// 日期  
        /// </summary>  
        public Nullable<System.DateTime> DATE { get; set; } 
    }
}
