//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class listofpurchaseinvoices
    {
    
        /// <summary>  
        /// 发票清单表ID  
        /// </summary>  
        public int invoicelist { get; set; } 
    
        /// <summary>  
        /// 详表ID  
        /// </summary>  
        public Nullable<int> lineint { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string materialint { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string namematerial { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string specificationtype { get; set; } 
    
        /// <summary>  
        /// 单位  
        /// </summary>  
        public string company { get; set; } 
    
        /// <summary>  
        /// 发票数量  
        /// </summary>  
        public Nullable<int> invoicequantity { get; set; } 
    
        /// <summary>  
        /// 发票单价  
        /// </summary>  
        public Nullable<float> invoiceunitprice { get; set; } 
    
        /// <summary>  
        /// 发票金额  
        /// </summary>  
        public Nullable<float> invoiceamount { get; set; } 
    
        /// <summary>  
        /// 发票税率%  
        /// </summary>  
        public Nullable<float> invoicetaxrate { get; set; } 
    
        /// <summary>  
        /// 发票税额  
        /// </summary>  
        public Nullable<float> invoicetax { get; set; } 
    
        /// <summary>  
        /// 发票含税金额  
        /// </summary>  
        public Nullable<float> invoicetaxableamount { get; set; } 
    
        /// <summary>  
        /// 汇差  
        /// </summary>  
        public Nullable<float> sinkdifference { get; set; } 
    
        /// <summary>  
        /// 价差  
        /// </summary>  
        public Nullable<float> spread { get; set; } 
    
        /// <summary>  
        /// 价差本位币  
        /// </summary>  
        public Nullable<float> standardcurrency { get; set; } 
    
        /// <summary>  
        /// 差额合计  
        /// </summary>  
        public Nullable<float> totaldifference { get; set; } 
    
        /// <summary>  
        /// 来源单别  
        /// </summary>  
        public string sourcelist { get; set; } 
    
        /// <summary>  
        /// 来源单号  
        /// </summary>  
        public string sourceno { get; set; } 
    
        /// <summary>  
        /// 分录备注  
        /// </summary>  
        public string notestoentries { get; set; } 
    }
}
