//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainlistofpurchaseinvoices
    {
    
        /// <summary>  
        /// 发票主表ID  
        /// </summary>  
        public int storageid { get; set; } 
    
        /// <summary>  
        /// 供货商ID  
        /// </summary>  
        public string citationid { get; set; } 
    
        /// <summary>  
        /// 供货商名称  
        /// </summary>  
        public string clientsupply { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public Nullable<System.DateTime> storagedate { get; set; } 
    
        /// <summary>  
        /// 单据类型  
        /// </summary>  
        public string documenttype { get; set; } 
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string documentint { get; set; } 
    
        /// <summary>  
        /// 单价是否含税  
        /// </summary>  
        public Nullable<int> taxincluded { get; set; } 
    
        /// <summary>  
        /// 发票号码  
        /// </summary>  
        public string invoiceint { get; set; } 
    
        /// <summary>  
        /// 采购核对状态  
        /// </summary>  
        public string checkstatus { get; set; } 
    
        /// <summary>  
        /// 发票类型  
        /// </summary>  
        public Nullable<int> invoicetype { get; set; } 
    
        /// <summary>  
        /// 凭证编号  
        /// </summary>  
        public string voucherint { get; set; } 
    
        /// <summary>  
        /// 币别  
        /// </summary>  
        public string currency { get; set; } 
    
        /// <summary>  
        /// 差价凭证编号  
        /// </summary>  
        public string CertificateNo { get; set; } 
    
        /// <summary>  
        /// 汇率  
        /// </summary>  
        public Nullable<float> exchangerate { get; set; } 
    
        /// <summary>  
        /// 采购人员  
        /// </summary>  
        public string Purchaser { get; set; } 
    
        /// <summary>  
        /// 所属部门  
        /// </summary>  
        public string subordinatedepartments { get; set; } 
    
        /// <summary>  
        /// 账款归属  
        /// </summary>  
        public string attributionofaccounts { get; set; } 
    
        /// <summary>  
        /// 付款条件  
        /// </summary>  
        public string termofpayment { get; set; } 
    
        /// <summary>  
        /// 付款条件天数  
        /// </summary>  
        public Nullable<int> daysofpaymentterms { get; set; } 
    
        /// <summary>  
        /// 付款日期  
        /// </summary>  
        public Nullable<System.DateTime> dateofpayment { get; set; } 
    
        /// <summary>  
        /// 账款月份  
        /// </summary>  
        public Nullable<System.DateTime> accountmonth { get; set; } 
    
        /// <summary>  
        /// 结算方式1  
        /// </summary>  
        public string paystrike1 { get; set; } 
    
        /// <summary>  
        /// 结算方式2  
        /// </summary>  
        public string paystrike2 { get; set; } 
    
        /// <summary>  
        /// 结算方式3  
        /// </summary>  
        public string paystrike3 { get; set; } 
    
        /// <summary>  
        /// 金额1  
        /// </summary>  
        public Nullable<float> paymoney1 { get; set; } 
    
        /// <summary>  
        /// 金额2  
        /// </summary>  
        public Nullable<float> paymoney2 { get; set; } 
    
        /// <summary>  
        /// 金额3  
        /// </summary>  
        public Nullable<float> paymoney3 { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string systempersonnel { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string reviewpersonne { get; set; } 
    
        /// <summary>  
        /// 所属项目  
        /// </summary>  
        public string subordinateprojects { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> enables { get; set; } 
    
        /// <summary>  
        /// 是否审核  
        /// </summary>  
        public Nullable<int> isaditing { get; set; } 
    }
}
