//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiel
    {
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string Matid { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string Matname { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string Matspec { get; set; } 
    
        /// <summary>  
        /// 物料类别（伪外键）  
        /// </summary>  
        public string Mattypeid { get; set; } 
    
        /// <summary>  
        /// 物料类别名称  
        /// </summary>  
        public string Mattypename { get; set; } 
    
        /// <summary>  
        /// 建议售价  
        /// </summary>  
        public Nullable<float> Matadviceprice { get; set; } 
    
        /// <summary>  
        /// 售价A  
        /// </summary>  
        public Nullable<float> Matadvicepricea { get; set; } 
    
        /// <summary>  
        /// 售价B  
        /// </summary>  
        public Nullable<float> Matadvicepriceb { get; set; } 
    
        /// <summary>  
        /// 售价C  
        /// </summary>  
        public Nullable<float> Matadvicepricec { get; set; } 
    
        /// <summary>  
        /// 售价D  
        /// </summary>  
        public Nullable<float> Matadvicepriced { get; set; } 
    
        /// <summary>  
        /// 售价E  
        /// </summary>  
        public Nullable<float> Matadvicepricee { get; set; } 
    
        /// <summary>  
        /// 标准进价  
        /// </summary>  
        public Nullable<float> Matstandardprice { get; set; } 
    
        /// <summary>  
        /// 物料型态  
        /// </summary>  
        public string Matshape { get; set; } 
    
        /// <summary>  
        /// 是否含税  
        /// </summary>  
        public Nullable<int> Matifduty { get; set; } 
    
        /// <summary>  
        /// 税率  
        /// </summary>  
        public Nullable<float> Matdutyrate { get; set; } 
    
        /// <summary>  
        /// 采购提前期  
        /// </summary>  
        public Nullable<int> Matstockaheaddate { get; set; } 
    
        /// <summary>  
        /// 主供应商  
        /// </summary>  
        public string Matmainafford { get; set; } 
    
        /// <summary>  
        /// 主供应商ID  
        /// </summary>  
        public string Matmainaffordid { get; set; } 
    
        /// <summary>  
        /// 呆滞起计天数  
        /// </summary>  
        public Nullable<int> Matgawpdate { get; set; } 
    
        /// <summary>  
        /// 停用日期  
        /// </summary>  
        public Nullable<System.DateTime> Matstopdate { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Matremark { get; set; } 
    
        /// <summary>  
        /// 计量单位  
        /// </summary>  
        public string Matunit { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> ENABLE { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
