//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erpEntities : DbContext
    {
        public erpEntities()
            : base("name=erpEntities")
        {
            //设置不验证EF自带 特性
            base.Configuration.ValidateOnSaveEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountmoneydetail> accountmoneydetail { get; set; }
        public DbSet<advance> advance { get; set; }
        public DbSet<advancedetails> advancedetails { get; set; }
        public DbSet<advancegather> advancegather { get; set; }
        public DbSet<advancegatherdetails> advancegatherdetails { get; set; }
        public DbSet<apportiondetails> apportiondetails { get; set; }
        public DbSet<apportionresult> apportionresult { get; set; }
        public DbSet<apportionwise> apportionwise { get; set; }
        public DbSet<calculateunit> calculateunit { get; set; }
        public DbSet<checkdetail> checkdetail { get; set; }
        public DbSet<@checked> @checked { get; set; }
        public DbSet<clashfund> clashfund { get; set; }
        public DbSet<clashfunddetailsone> clashfunddetailsone { get; set; }
        public DbSet<client> client { get; set; }
        public DbSet<clientaddress> clientaddress { get; set; }
        public DbSet<clienttype> clienttype { get; set; }
        public DbSet<currencytype> currencytype { get; set; }
        public DbSet<depothead> depothead { get; set; }
        public DbSet<depotheaddetails> depotheaddetails { get; set; }
        public DbSet<depttab> depttab { get; set; }
        public DbSet<dsdaarea> dsdaarea { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<generalledger> generalledger { get; set; }
        public DbSet<listofpurchaseinvoices> listofpurchaseinvoices { get; set; }
        public DbSet<mainlistofpurchaseinvoices> mainlistofpurchaseinvoices { get; set; }
        public DbSet<materiel> materiel { get; set; }
        public DbSet<materieltype> materieltype { get; set; }
        public DbSet<movedetails> movedetails { get; set; }
        public DbSet<moveprice> moveprice { get; set; }
        public DbSet<movepricedetail> movepricedetail { get; set; }
        public DbSet<movestorage> movestorage { get; set; }
        public DbSet<othercome> othercome { get; set; }
        public DbSet<othercomedetail> othercomedetail { get; set; }
        public DbSet<otheroutdetail> otheroutdetail { get; set; }
        public DbSet<otheroutmain> otheroutmain { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<paymentdetails> paymentdetails { get; set; }
        public DbSet<procurementinvoicebreakdown> procurementinvoicebreakdown { get; set; }
        public DbSet<provideinfo> provideinfo { get; set; }
        public DbSet<recededetails> recededetails { get; set; }
        public DbSet<revenuechargetype> revenuechargetype { get; set; }
        public DbSet<saleaccountdetails> saleaccountdetails { get; set; }
        public DbSet<sell_order> sell_order { get; set; }
        public DbSet<sell_order_item> sell_order_item { get; set; }
        public DbSet<sell_quote> sell_quote { get; set; }
        public DbSet<sell_quote_item> sell_quote_item { get; set; }
        public DbSet<sellinvoice> sellinvoice { get; set; }
        public DbSet<sellinvoiceitem> sellinvoiceitem { get; set; }
        public DbSet<sellinvoicelist> sellinvoicelist { get; set; }
        public DbSet<stagnation> stagnation { get; set; }
        public DbSet<stockapply> stockapply { get; set; }
        public DbSet<stockapplydetails> stockapplydetails { get; set; }
        public DbSet<stockapplytype> stockapplytype { get; set; }
        public DbSet<stockapportion> stockapportion { get; set; }
        public DbSet<stockinquire> stockinquire { get; set; }
        public DbSet<stockinquiredetails> stockinquiredetails { get; set; }
        public DbSet<stockorder> stockorder { get; set; }
        public DbSet<stockorderdetails> stockorderdetails { get; set; }
        public DbSet<stockrecede> stockrecede { get; set; }
        public DbSet<stockstoragedetails> stockstoragedetails { get; set; }
        public DbSet<stockstoragetable> stockstoragetable { get; set; }
        public DbSet<storage> storage { get; set; }
        public DbSet<supplieraddress> supplieraddress { get; set; }
        public DbSet<takeadvancedetails> takeadvancedetails { get; set; }
        public DbSet<takeadvancegatherdetails> takeadvancegatherdetails { get; set; }
    }
}
