//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class movedetails
    {
    
        /// <summary>  
        /// 单号  
        /// </summary>  
        public int DMdsno { get; set; } 
    
        /// <summary>  
        /// 单据号码(单号)  
        /// </summary>  
        public string DMdsmseno { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string Dmdsmaterieltype { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string Dmdsmaterielname { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string Dmdsmaterielspecs { get; set; } 
    
        /// <summary>  
        /// 单位  
        /// </summary>  
        public string Dmdsmaterielunit { get; set; } 
    
        /// <summary>  
        /// 数量  
        /// </summary>  
        public string Dmdsmaterielnum { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string DMdsremark { get; set; } 
    
        /// <summary>  
        /// 保留字段1  
        /// </summary>  
        public string DMespreservingone { get; set; } 
    
        /// <summary>  
        /// 保留字段2  
        /// </summary>  
        public string Dmespreservingtwo { get; set; } 
    
        /// <summary>  
        /// 默认1使用，0：不使用	使用有效期  
        /// </summary>  
        public Nullable<int> Denables { get; set; } 
    }
}
