//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class moveprice
    {
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public Nullable<System.DateTime> movedate { get; set; } 
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string moveorderNo { get; set; } 
    
        /// <summary>  
        /// 增值科目  
        /// </summary>  
        public string moveadjust { get; set; } 
    
        /// <summary>  
        /// 仓库编号  
        /// </summary>  
        public string movestorageNo { get; set; } 
    
        /// <summary>  
        /// 制单人员
              
        /// </summary>  
        public string movemake { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string movecheck { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string moveremark { get; set; } 
    
        /// <summary>  
        /// 审核状态  
        /// </summary>  
        public Nullable<int> moveAuditingState { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string safetytwo { get; set; } 
    
        /// <summary>  
        /// 减值科目  
        /// </summary>  
        public string Moveadjian { get; set; } 
    }
}
