//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class movepricedetail
    {
    
        /// <summary>  
        /// 详表ID  
        /// </summary>  
        public int Moveinile { get; set; } 
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string moveorderNo { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string Movematerielno { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string Movematerielname { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string Movespectype { get; set; } 
    
        /// <summary>  
        /// 单位  
        /// </summary>  
        public string Moveunit { get; set; } 
    
        /// <summary>  
        /// 库存量  
        /// </summary>  
        public Nullable<int> Movestocks { get; set; } 
    
        /// <summary>  
        /// 平均成本  
        /// </summary>  
        public Nullable<int> moveaveragecost { get; set; } 
    
        /// <summary>  
        /// 单价  
        /// </summary>  
        public Nullable<int> moveprice { get; set; } 
    
        /// <summary>  
        /// 调价金额  
        /// </summary>  
        public Nullable<int> movemoveprice { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string safetytwo { get; set; } 
    }
}
