//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class movestorage
    {
    
        /// <summary>  
        /// 单据号码(单号)  
        /// </summary>  
        public int Mseno { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public Nullable<System.DateTime> msedate { get; set; } 
    
        /// <summary>  
        /// 调出库仓（仓库编号）  
        /// </summary>  
        public string Mseoutstorage { get; set; } 
    
        /// <summary>  
        /// 调入库仓（仓库编号）  
        /// </summary>  
        public string mseinsertstor { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string mseemployee { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string mesAuditingemp { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Mesremark { get; set; } 
    
        /// <summary>  
        /// 审核状态  
        /// </summary>  
        public string messtate { get; set; } 
    
        /// <summary>  
        /// 是否可用  
        /// </summary>  
        public string Mestrash { get; set; } 
    
        /// <summary>  
        /// 保留字段1  
        /// </summary>  
        public string Mespreservingone { get; set; } 
    
        /// <summary>  
        /// 保留字段2  
        /// </summary>  
        public string mespreservingtwo { get; set; } 
    
        /// <summary>  
        /// 保留字段3  
        /// </summary>  
        public string Mespreservingthree { get; set; } 
    }
}
