//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class othercome
    {
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string Othcomeid { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public Nullable<System.DateTime> Othcomedate { get; set; } 
    
        /// <summary>  
        /// 入库类型  
        /// </summary>  
        public string othcometypeid { get; set; } 
    
        /// <summary>  
        /// 仓库  
        /// </summary>  
        public string Othcomestore { get; set; } 
    
        /// <summary>  
        /// 入库人员  
        /// </summary>  
        public string Othcomename { get; set; } 
    
        /// <summary>  
        /// 所属部门  
        /// </summary>  
        public string Othcomedept { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string Othcomemakemanid { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string Othcomerepeatuserid { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string tone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string ttwo { get; set; } 
    }
}
