//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class otheroutmain
    {
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string Othid { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public Nullable<System.DateTime> Othdate { get; set; } 
    
        /// <summary>  
        /// 出库类型  
        /// </summary>  
        public string othouttypeid { get; set; } 
    
        /// <summary>  
        /// 仓库  
        /// </summary>  
        public string othstore { get; set; } 
    
        /// <summary>  
        /// 出库人名  
        /// </summary>  
        public string Othoutname { get; set; } 
    
        /// <summary>  
        /// 所属部门  
        /// </summary>  
        public string Othdept { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string Othmakemanid { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string Othrepeatuserid { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Oonw { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string otwo { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string otherr { get; set; } 
    }
}
