//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class othercomedetail
    {
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string Othcomeid { get; set; } 
    
        /// <summary>  
        /// 栏号  
        /// </summary>  
        public string Othcomeno { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string Othcomemertialsid { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string Othcomemertialname { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string Othcometypes { get; set; } 
    
        /// <summary>  
        /// 单位  
        /// </summary>  
        public string Othcomeunits { get; set; } 
    
        /// <summary>  
        /// 数量  
        /// </summary>  
        public Nullable<int> Othcomeamount { get; set; } 
    
        /// <summary>  
        /// 单价  
        /// </summary>  
        public string Othmoney { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public Nullable<int> Jine { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Beizhu { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Ziduanone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Ziduantwo { get; set; } 
    }
}
