//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class otheroutdetail
    {
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string otheroutid { get; set; } 
    
        /// <summary>  
        /// 栏号  
        /// </summary>  
        public string Othoutlineno { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string Othoutmertialsid { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string Othoutmertialname { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string Othouttypes { get; set; } 
    
        /// <summary>  
        /// 单位  
        /// </summary>  
        public string Othoutunits { get; set; } 
    
        /// <summary>  
        /// 数量  
        /// </summary>  
        public Nullable<int> Othoutamount { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string othoutremark { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Tone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Ttwo { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Ttherr { get; set; } 
    }
}
