//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class procurementinvoicebreakdown
    {
    
        /// <summary>  
        /// 发票明细表ID  
        /// </summary>  
        public int invoiceddetailsid { get; set; } 
    
        /// <summary>  
        /// 行号  
        /// </summary>  
        public Nullable<int> lineint { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string materialint { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string namematerial { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string specificationtype { get; set; } 
    
        /// <summary>  
        /// 单位名称  
        /// </summary>  
        public string nameofunit { get; set; } 
    
        /// <summary>  
        /// 数量  
        /// </summary>  
        public Nullable<int> num { get; set; } 
    
        /// <summary>  
        /// 单价  
        /// </summary>  
        public Nullable<float> unitprice { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public Nullable<float> amountofmoney { get; set; } 
    
        /// <summary>  
        /// 税率%  
        /// </summary>  
        public Nullable<float> taxrate { get; set; } 
    
        /// <summary>  
        /// 税额  
        /// </summary>  
        public Nullable<float> taxamount { get; set; } 
    
        /// <summary>  
        /// 含税金额  
        /// </summary>  
        public Nullable<float> taxableamount { get; set; } 
    
        /// <summary>  
        /// 未进数量  
        /// </summary>  
        public Nullable<int> unenteredquantity { get; set; } 
    
        /// <summary>  
        /// 采购订单号  
        /// </summary>  
        public string purchasingorderint { get; set; } 
    
        /// <summary>  
        /// 分录备注  
        /// </summary>  
        public string notestoentries { get; set; } 
    }
}
