//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class provideinfo
    {
    
        /// <summary>  
        /// 供应商编号  
        /// </summary>  
        public int Peoid { get; set; } 
    
        /// <summary>  
        /// 供应商全称  
        /// </summary>  
        public string Peoname { get; set; } 
    
        /// <summary>  
        /// 供应商简称  
        /// </summary>  
        public string Peoshortname { get; set; } 
    
        /// <summary>  
        /// 帐款归属  
        /// </summary>  
        public string Peoascription { get; set; } 
    
        /// <summary>  
        /// 供应商类型表id  
        /// </summary>  
        public string Peopeeid { get; set; } 
    
        /// <summary>  
        /// 供应商类型表名称（新增）  
        /// </summary>  
        public string Peopeename { get; set; } 
    
        /// <summary>  
        /// 地区  
        /// </summary>  
        public string Peoarea { get; set; } 
    
        /// <summary>  
        /// 负责人  
        /// </summary>  
        public string Peoprincipal { get; set; } 
    
        /// <summary>  
        /// 联系人  
        /// </summary>  
        public string Peolinkman { get; set; } 
    
        /// <summary>  
        /// 联系电话一  
        /// </summary>  
        public string Peophoneone { get; set; } 
    
        /// <summary>  
        /// 联系电话二  
        /// </summary>  
        public string Peophonetwo { get; set; } 
    
        /// <summary>  
        /// 移动电话  
        /// </summary>  
        public string Peomobilephone { get; set; } 
    
        /// <summary>  
        /// 银行帐号  
        /// </summary>  
        public string Peobankaccounts { get; set; } 
    
        /// <summary>  
        /// 开户银行  
        /// </summary>  
        public string Peoopenbank { get; set; } 
    
        /// <summary>  
        /// （业务人员编号）  
        /// </summary>  
        public string Peoempid { get; set; } 
    
        /// <summary>  
        /// （业务人员名称）  
        /// </summary>  
        public string Peoempname { get; set; } 
    
        /// <summary>  
        /// 行业别  
        /// </summary>  
        public string Peocalling { get; set; } 
    
        /// <summary>  
        /// 电子邮件  
        /// </summary>  
        public string Peoemail { get; set; } 
    
        /// <summary>  
        /// 网址  
        /// </summary>  
        public string Peoweb { get; set; } 
    
        /// <summary>  
        /// 传真号码  
        /// </summary>  
        public string Peofaxes { get; set; } 
    
        /// <summary>  
        /// 建立日期  
        /// </summary>  
        public string Peocreatedate { get; set; } 
    
        /// <summary>  
        /// 信用等级  
        /// </summary>  
        public string Peocreditclass { get; set; } 
    
        /// <summary>  
        /// 帐款额度  
        /// </summary>  
        public Nullable<decimal> Peozhangkuanedu { get; set; } 
    
        /// <summary>  
        /// 剩余额度  
        /// </summary>  
        public Nullable<decimal> Peoremainedu { get; set; } 
    
        /// <summary>  
        /// 每月结帐日  
        /// </summary>  
        public Nullable<decimal> Peomonthreckoning { get; set; } 
    
        /// <summary>  
        /// 期初预付款  
        /// </summary>  
        public Nullable<decimal> Peoqcprepaymoney { get; set; } 
    
        /// <summary>  
        /// 期初应付款  
        /// </summary>  
        public Nullable<decimal> Peoqcdealmoney { get; set; } 
    
        /// <summary>  
        /// 期末预付款  
        /// </summary>  
        public Nullable<decimal> Peoqmprepaymoney { get; set; } 
    
        /// <summary>  
        /// 期末应付款  
        /// </summary>  
        public Nullable<decimal> Peoqmdealmoney { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Peoremark { get; set; } 
    
        /// <summary>  
        /// 是否废码  
        /// </summary>  
        public Nullable<int> Peotrash { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> Enables { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
