//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenuechargetype
    {
    
        /// <summary>  
        /// 编号  
        /// </summary>  
        public string FareClassId { get; set; } 
    
        /// <summary>  
        /// 名称  
        /// </summary>  
        public string FareClassName { get; set; } 
    
        /// <summary>  
        /// 英文名称  
        /// </summary>  
        public string EngName { get; set; } 
    
        /// <summary>  
        /// 会计科目  
        /// </summary>  
        public string AccSubjectId { get; set; } 
    
        /// <summary>  
        /// 科目名称  
        /// </summary>  
        public string AccSubjectName { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Memo { get; set; } 
    }
}
