//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleaccountdetails
    {
    
        /// <summary>  
        /// 主键ID  
        /// </summary>  
        public int Minusaddid { get; set; } 
    
        /// <summary>  
        /// 来源单别  
        /// </summary>  
        public int Sinid { get; set; } 
    
        /// <summary>  
        /// 来源单别名称  
        /// </summary>  
        public string Sinname { get; set; } 
    
        /// <summary>  
        /// 来源单号  
        /// </summary>  
        public string Originbillid { get; set; } 
    
        /// <summary>  
        /// 来源单据日期  
        /// </summary>  
        public System.DateTime Nowdate { get; set; } 
    
        /// <summary>  
        /// 客户编号client(cliid)  
        /// </summary>  
        public int Cliid { get; set; } 
    
        /// <summary>  
        /// 日期  
        /// </summary>  
        public System.DateTime Showdate { get; set; } 
    
        /// <summary>  
        /// 原单金额  
        /// </summary>  
        public float Originoddmoney { get; set; } 
    
        /// <summary>  
        /// 现行余额  
        /// </summary>  
        public float Currentlybalance { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Remark { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public int Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
