//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell_order
    {
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string bill_id { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public Nullable<System.DateTime> bill_date { get; set; } 
    
        /// <summary>  
        /// 销售订单类型  
        /// </summary>  
        public string bill_type { get; set; } 
    
        /// <summary>  
        /// 客户订单  
        /// </summary>  
        public string chi_order { get; set; } 
    
        /// <summary>  
        /// 地址  
        /// </summary>  
        public string chiplace { get; set; } 
    
        /// <summary>  
        /// 单况（1.未结案。2.已结案 3.已无效）  
        /// </summary>  
        public Nullable<int> order_status { get; set; } 
    
        /// <summary>  
        /// 币别  
        /// </summary>  
        public Nullable<int> currency { get; set; } 
    
        /// <summary>  
        /// 单价是否含税  
        /// </summary>  
        public Nullable<bool> price_whether_tax { get; set; } 
    
        /// <summary>  
        /// 业务人员编号  
        /// </summary>  
        public Nullable<int> emp_id { get; set; } 
    
        /// <summary>  
        /// 业务人员姓名  
        /// </summary>  
        public string emp_name { get; set; } 
    
        /// <summary>  
        /// 部门编号  
        /// </summary>  
        public Nullable<int> dep_id { get; set; } 
    
        /// <summary>  
        /// 部门名字  
        /// </summary>  
        public string dep_name { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string mark_emp_name { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string auditing_emp_name { get; set; } 
    
        /// <summary>  
        /// 0未审核  1已审核  
        /// </summary>  
        public Nullable<int> check_state { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string remark { get; set; } 
    
        /// <summary>  
        /// 收款条件(外键)  
        /// </summary>  
        public Nullable<int> collection_terms { get; set; } 
    
        /// <summary>  
        /// 收款天数  
        /// </summary>  
        public Nullable<int> collection_day { get; set; } 
    
        /// <summary>  
        /// 收款日期  
        /// </summary>  
        public Nullable<System.DateTime> collection_date { get; set; } 
    
        /// <summary>  
        /// 所属项目(外键)  
        /// </summary>  
        public Nullable<int> belong_project { get; set; } 
    
        /// <summary>  
        /// 是否已被删除  
        /// </summary>  
        public Nullable<int> is_exist { get; set; } 
    }
}
