//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell_quote
    {
    
        /// <summary>  
        /// 单价号码  
        /// </summary>  
        public string bill_id { get; set; } 
    
        /// <summary>  
        /// 单击日期  
        /// </summary>  
        public Nullable<System.DateTime> bill_date { get; set; } 
    
        /// <summary>  
        /// 客户编号  
        /// </summary>  
        public string CLIENT { get; set; } 
    
        /// <summary>  
        /// 客户简称  
        /// </summary>  
        public string cli_short_name { get; set; } 
    
        /// <summary>  
        /// 地址编号  
        /// </summary>  
        public Nullable<int> cli_place_id { get; set; } 
    
        /// <summary>  
        /// 客户地址  
        /// </summary>  
        public string cli_place { get; set; } 
    
        /// <summary>  
        /// 1.未结案。2.已结案 3.已无效  
        /// </summary>  
        public Nullable<int> order_status { get; set; } 
    
        /// <summary>  
        /// 币别  
        /// </summary>  
        public Nullable<int> currency { get; set; } 
    
        /// <summary>  
        /// 单价是否含税  
        /// </summary>  
        public Nullable<bool> price_whether_tax { get; set; } 
    
        /// <summary>  
        /// 业务人员编号  
        /// </summary>  
        public Nullable<int> emp_id { get; set; } 
    
        /// <summary>  
        /// 业务人员姓名  
        /// </summary>  
        public string emp_name { get; set; } 
    
        /// <summary>  
        /// 部门编号  
        /// </summary>  
        public Nullable<int> dep_id { get; set; } 
    
        /// <summary>  
        /// 部门名称  
        /// </summary>  
        public string dep_name { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string make_emp_name { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string auditing_emp_name { get; set; } 
    
        /// <summary>  
        /// 0.未审核  1.已审核  
        /// </summary>  
        public Nullable<int> check_state { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string remark { get; set; } 
    
        /// <summary>  
        /// 合计金额  
        /// </summary>  
        public Nullable<float> total_money { get; set; } 
    
        /// <summary>  
        /// 合计税额  
        /// </summary>  
        public Nullable<float> tatal_tax { get; set; } 
    
        /// <summary>  
        /// 合计含税金额  
        /// </summary>  
        public Nullable<float> total_tax_money { get; set; } 
    
        /// <summary>  
        /// 是否已删除  
        /// </summary>  
        public Nullable<bool> is_exist { get; set; } 
    }
}
