//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellinvoice
    {
    
        /// <summary>  
        /// 单据号码  
        /// </summary>  
        public string bill_id { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public Nullable<System.DateTime> bill_date { get; set; } 
    
        /// <summary>  
        /// 单据类型  
        /// </summary>  
        public string bill_type { get; set; } 
    
        /// <summary>  
        /// 客户id  
        /// </summary>  
        public Nullable<int> chi_id { get; set; } 
    
        /// <summary>  
        /// 客户姓名  
        /// </summary>  
        public string chi_name { get; set; } 
    
        /// <summary>  
        /// 销售核对状态  
        /// </summary>  
        public Nullable<int> sell_check_state { get; set; } 
    
        /// <summary>  
        /// 0未审核  1已审核  
        /// </summary>  
        public Nullable<int> check_state { get; set; } 
    
        /// <summary>  
        /// 币别  
        /// </summary>  
        public Nullable<int> currency { get; set; } 
    
        /// <summary>  
        /// 单价是否含税  
        /// </summary>  
        public Nullable<bool> price_whether_tax { get; set; } 
    
        /// <summary>  
        /// 业务人员编号  
        /// </summary>  
        public Nullable<int> emp_id { get; set; } 
    
        /// <summary>  
        /// 业务人员姓名  
        /// </summary>  
        public string emp_name { get; set; } 
    
        /// <summary>  
        /// 部门编号  
        /// </summary>  
        public Nullable<int> dep_id { get; set; } 
    
        /// <summary>  
        /// 部门名字  
        /// </summary>  
        public string dep_name { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string mark_emp_name { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string auditing_emp_name { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string remark { get; set; } 
    
        /// <summary>  
        /// 收款条件(外键)  
        /// </summary>  
        public Nullable<int> collection_terms { get; set; } 
    
        /// <summary>  
        /// 收款天数  
        /// </summary>  
        public Nullable<int> collection_day { get; set; } 
    
        /// <summary>  
        /// 收款日期  
        /// </summary>  
        public Nullable<System.DateTime> collection_date { get; set; } 
    
        /// <summary>  
        /// 所属项目(外键)  
        /// </summary>  
        public Nullable<int> belong_project { get; set; } 
    
        /// <summary>  
        /// 是否已被删除  
        /// </summary>  
        public Nullable<int> is_exist { get; set; } 
    
        /// <summary>  
        /// 发票类型id  
        /// </summary>  
        public Nullable<int> invoice_id { get; set; } 
    
        /// <summary>  
        /// 发票号码  
        /// </summary>  
        public string invoice_number { get; set; } 
    
        /// <summary>  
        /// 结算方式1  
        /// </summary>  
        public string settle_way_one { get; set; } 
    
        /// <summary>  
        /// 结算方式1金额  
        /// </summary>  
        public Nullable<float> settle_money_one { get; set; } 
    
        /// <summary>  
        /// 结算方式2  
        /// </summary>  
        public string settle_way_two { get; set; } 
    
        /// <summary>  
        /// 结算方式2金额  
        /// </summary>  
        public Nullable<float> settle_money_two { get; set; } 
    }
}
