//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockstoragedetails
    {
    
        /// <summary>  
        /// 引用采购入库单单号  
        /// </summary>  
        public string Storagedetailno { get; set; } 
    
        /// <summary>  
        /// 引用物料文件ID  
        /// </summary>  
        public string Materielid { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string Materielname { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string TYPES { get; set; } 
    
        /// <summary>  
        /// 单位  
        /// </summary>  
        public string Units { get; set; } 
    
        /// <summary>  
        /// 数量  
        /// </summary>  
        public Nullable<int> Amount { get; set; } 
    
        /// <summary>  
        /// 折扣前单价  
        /// </summary>  
        public Nullable<float> Rebateprice { get; set; } 
    
        /// <summary>  
        /// 折扣  
        /// </summary>  
        public Nullable<float> Rebate { get; set; } 
    
        /// <summary>  
        /// 单价  
        /// </summary>  
        public Nullable<float> Unitprice { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public Nullable<float> Moneys { get; set; } 
    
        /// <summary>  
        /// 税率  
        /// </summary>  
        public Nullable<float> Cess { get; set; } 
    
        /// <summary>  
        /// 税额  
        /// </summary>  
        public Nullable<float> Tax { get; set; } 
    
        /// <summary>  
        /// 含税金额  
        /// </summary>  
        public Nullable<float> Taxmoneys { get; set; } 
    
        /// <summary>  
        /// 来源单别  
        /// </summary>  
        public string Origintype { get; set; } 
    
        /// <summary>  
        /// 来源单号  
        /// </summary>  
        public string Originno { get; set; } 
    
        /// <summary>  
        /// 是否赠品  
        /// </summary>  
        public string Present { get; set; } 
    
        /// <summary>  
        /// 分摊费用  
        /// </summary>  
        public Nullable<float> Apportionmoney { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    
        /// <summary>  
        /// 详表ID  
        /// </summary>  
        public string StockstorageDetail { get; set; } 
    }
}
