//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockorder
    {
    
        /// <summary>  
        /// 单据号  
        /// </summary>  
        public string Stoid { get; set; } 
    
        /// <summary>  
        /// 日期  
        /// </summary>  
        public System.DateTime Stodate { get; set; } 
    
        /// <summary>  
        /// 供货商  
        /// </summary>  
        public string Stopeoname { get; set; } 
    
        /// <summary>  
        /// 供货商编号  
        /// </summary>  
        public string Stopeoid { get; set; } 
    
        /// <summary>  
        /// 供货商地址  
        /// </summary>  
        public string Stopeoadress { get; set; } 
    
        /// <summary>  
        /// 单价是否含税：1-含税，2-未税  
        /// </summary>  
        public string Stoistax { get; set; } 
    
        /// <summary>  
        /// 单况：1-未结案，2-已结案，3-无效  
        /// </summary>  
        public int Stostate { get; set; } 
    
        /// <summary>  
        /// 送货地址  
        /// </summary>  
        public string Stoadress { get; set; } 
    
        /// <summary>  
        /// 采购人员  
        /// </summary>  
        public string Stoempstock { get; set; } 
    
        /// <summary>  
        /// 伪外键:采购人员id  
        /// </summary>  
        public string Stopersonid { get; set; } 
    
        /// <summary>  
        /// 采购部门  
        /// </summary>  
        public string Stodept { get; set; } 
    
        /// <summary>  
        /// 伪外键:部门id  
        /// </summary>  
        public string Stodeptid { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string Stoempname { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string Stoempcheck { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Stomark { get; set; } 
    
        /// <summary>  
        /// 审核状态  
        /// </summary>  
        public int Checkstate { get; set; } 
    
        /// <summary>  
        /// 保存（采购订单）  
        /// </summary>  
        public string Stockordername { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public int Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
