//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockapplytype
    {
    
        /// <summary>  
        /// 类型编号  
        /// </summary>  
        public string Aptid { get; set; } 
    
        /// <summary>  
        /// 类型名称  
        /// </summary>  
        public string Aptname { get; set; } 
    
        /// <summary>  
        /// 英文名称  
        /// </summary>  
        public string Aptename { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Aptremark { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public int ENABLE { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
