//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockinquire
    {
    
        /// <summary>  
        /// 询价单编号  
        /// </summary>  
        public string Stoid { get; set; } 
    
        /// <summary>  
        /// 供应商  
        /// </summary>  
        public string Stopname { get; set; } 
    
        /// <summary>  
        /// 伪外键(供应商主文件)  
        /// </summary>  
        public string Stopid { get; set; } 
    
        /// <summary>  
        /// 供应商地址  
        /// </summary>  
        public string Stopaddress { get; set; } 
    
        /// <summary>  
        /// 单据日期  
        /// </summary>  
        public System.DateTime Sotdate { get; set; } 
    
        /// <summary>  
        /// 有效日期  
        /// </summary>  
        public System.DateTime Stoavdate { get; set; } 
    
        /// <summary>  
        /// 是否含税(含税/未含税)  
        /// </summary>  
        public string Stoistax { get; set; } 
    
        /// <summary>  
        /// 送货地址  
        /// </summary>  
        public string Stodaddress { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string Stomakeperson { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string Stoauditingperson { get; set; } 
    
        /// <summary>  
        /// 采购人员  
        /// </summary>  
        public string Stostockperson { get; set; } 
    
        /// <summary>  
        /// 伪外键(请购人员外键)  
        /// </summary>  
        public string Stopersonid { get; set; } 
    
        /// <summary>  
        /// 所属部门  
        /// </summary>  
        public string Stodept { get; set; } 
    
        /// <summary>  
        /// 伪外键(所属部门外键)  
        /// </summary>  
        public string Stodeptid { get; set; } 
    
        /// <summary>  
        /// 审核状态：未审核/已审核/无效  
        /// </summary>  
        public string Stoauditing { get; set; } 
    
        /// <summary>  
        /// 保存（“采购询价单”）  
        /// </summary>  
        public string Stockinquirename { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public int Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
