//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockapply
    {
    
        /// <summary>  
        /// 请购单编号  
        /// </summary>   
        public string Appid { get; set; } 
    
        /// <summary>  
        /// 请购单日期  
        /// </summary>  
        public System.DateTime Appdate { get; set; } 
    
        /// <summary>  
        /// 请购采购类型  
        /// </summary>  
        public string Apptype { get; set; } 
    
        /// <summary>  
        /// 单况：已结案/未结案/无效  
        /// </summary>  
        public int Appcircs { get; set; } 
    
        /// <summary>  
        /// 请购人员  
        /// </summary>  
        public string Appperson { get; set; } 
    
        /// <summary>  
        /// 伪外键：请购人员id  
        /// </summary>  
        public string Apppersonid { get; set; } 
    
        /// <summary>  
        /// 请购部门  
        /// </summary>  
        public string Appdept { get; set; } 
    
        /// <summary>  
        /// 伪外键：请购部门id  
        /// </summary>  
        public string Appdeptid { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string Appmaker { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string Appauditingperson { get; set; } 
    
        /// <summary>  
        /// 审核状态：未审核/已审核/无效  
        /// </summary>  
        public string Appauditing { get; set; } 
    
        /// <summary>  
        /// 保存（“采购请购”）  
        /// </summary>  
        public string Stockapplyname { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public int Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段 保存（“采购请购”）  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
