//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockinquiredetails
    {
    
        /// <summary>  
        /// 询价单编号  
        /// </summary>  
        public string Stoid { get; set; } 
    
        /// <summary>  
        /// 行号  
        /// </summary>  
        public int Sdarows { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string Sdamaterielid { get; set; } 
    
        /// <summary>  
        /// 物料名称  
        /// </summary>  
        public string Sdamateridlname { get; set; } 
    
        /// <summary>  
        /// 规格型号  
        /// </summary>  
        public string Sdamodel { get; set; } 
    
        /// <summary>  
        /// 单位名称  
        /// </summary>  
        public string Sdaunit { get; set; } 
    
        /// <summary>  
        /// 数量  
        /// </summary>  
        public int Sdanum { get; set; } 
    
        /// <summary>  
        /// 折前单价  
        /// </summary>  
        public float Sdaagioes { get; set; } 
    
        /// <summary>  
        /// 折数(%)  
        /// </summary>  
        public int Sdaagiocess { get; set; } 
    
        /// <summary>  
        /// 单价  
        /// </summary>  
        public float Sdaprice { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public float Sdamoney { get; set; } 
    
        /// <summary>  
        /// 税率(%)  
        /// </summary>  
        public int Sdacess { get; set; } 
    
        /// <summary>  
        /// 税额  
        /// </summary>  
        public float Sdataxmoney { get; set; } 
    
        /// <summary>  
        /// 含税金额  
        /// </summary>  
        public float Sdataxmoneys { get; set; } 
    
        /// <summary>  
        /// 赠品：是/否  
        /// </summary>  
        public int Sdaislargess { get; set; } 
    
        /// <summary>  
        /// 来源单号  
        /// </summary>  
        public string Sdaoriginid { get; set; } 
    
        /// <summary>  
        /// 来源单别  
        /// </summary>  
        public string Sdaorigintype { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Sdaremark { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public int Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
