//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockapportion
    {
    
        /// <summary>  
        /// 采购分摊单号  
        /// </summary>  
        public string Appid { get; set; } 
    
        /// <summary>  
        /// 分摊日期  
        /// </summary>  
        public Nullable<System.DateTime> Appdate { get; set; } 
    
        /// <summary>  
        /// 分摊方式  
        /// </summary>  
        public string Wisname { get; set; } 
    
        /// <summary>  
        /// 待摊金额  
        /// </summary>  
        public Nullable<float> Appamtmoney { get; set; } 
    
        /// <summary>  
        /// 制单人员  
        /// </summary>  
        public string Makeperson { get; set; } 
    
        /// <summary>  
        /// 复核人员  
        /// </summary>  
        public string Auditingperson { get; set; } 
    
        /// <summary>  
        /// 是否已审核  
        /// </summary>  
        public string Estate { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
