//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockorderdetails
    {
    
        /// <summary>  
        /// 栏号  
        /// </summary>  
        public string Sodlineid { get; set; } 
    
        /// <summary>  
        /// 单据号  
        /// </summary>  
        public string Sodid { get; set; } 
    
        /// <summary>  
        /// 物料编号  
        /// </summary>  
        public string Sodmaterielid { get; set; } 
    
        /// <summary>  
        /// (物料名称)  
        /// </summary>  
        public string Sodmatid { get; set; } 
    
        /// <summary>  
        /// (规格型号)  
        /// </summary>  
        public string Sodspec { get; set; } 
    
        /// <summary>  
        /// 数量  
        /// </summary>  
        public int Sodamount { get; set; } 
    
        /// <summary>  
        /// 折扣前单价  
        /// </summary>  
        public float Sodpreprice { get; set; } 
    
        /// <summary>  
        /// 折数（%）  
        /// </summary>  
        public int Sodagio { get; set; } 
    
        /// <summary>  
        /// 单价  
        /// </summary>  
        public float Sodprice { get; set; } 
    
        /// <summary>  
        /// 金额  
        /// </summary>  
        public float Sodsum { get; set; } 
    
        /// <summary>  
        /// 税率（%）  
        /// </summary>  
        public int Sodcess { get; set; } 
    
        /// <summary>  
        /// (税额)  
        /// </summary>  
        public float Sodsumcess { get; set; } 
    
        /// <summary>  
        /// (含税金额）  
        /// </summary>  
        public float Sodsumprice { get; set; } 
    
        /// <summary>  
        /// 预入库日  
        /// </summary>  
        public System.DateTime Sodpreincomestorage { get; set; } 
    
        /// <summary>  
        /// 是否赠品  
        /// </summary>  
        public string Sodpresent { get; set; } 
    
        /// <summary>  
        /// (来源单别)  
        /// </summary>  
        public string Sodorigintype { get; set; } 
    
        /// <summary>  
        /// (来源单号)  
        /// </summary>  
        public string Sodorigin { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 转单ID  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
