//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage
    {
    
        /// <summary>  
        /// 仓库编号  
        /// </summary>  
        public string Stoid { get; set; } 
    
        /// <summary>  
        /// 仓库名称  
        /// </summary>  
        public string Stoname { get; set; } 
    
        /// <summary>  
        /// 仓库简称  
        /// </summary>  
        public string Stosimplename { get; set; } 
    
        /// <summary>  
        /// 联系人  
        /// </summary>  
        public string Stoconnectper { get; set; } 
    
        /// <summary>  
        /// 联系人ID(新增)  
        /// </summary>  
        public string Stoempid { get; set; } 
    
        /// <summary>  
        /// 联系电话  
        /// </summary>  
        public string Stophone { get; set; } 
    
        /// <summary>  
        /// 仓库地址  
        /// </summary>  
        public string Stoaddress { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string Storemark { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public Nullable<int> Enables { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
