//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplieraddress
    {
    
        /// <summary>  
        /// 供应商地址id  
        /// </summary>  
        public string suaddrId { get; set; } 
    
        /// <summary>  
        /// 供应商地址  
        /// </summary>  
        public string suaddress { get; set; } 
    
        /// <summary>  
        /// 邮政编码  
        /// </summary>  
        public string suzipcode { get; set; } 
    
        /// <summary>  
        /// 联系人  
        /// </summary>  
        public string sulinkman { get; set; } 
    
        /// <summary>  
        /// 联系人职称  
        /// </summary>  
        public string sulinkmanprof { get; set; } 
    
        /// <summary>  
        /// 联系人电话  
        /// </summary>  
        public string sutelephone { get; set; } 
    
        /// <summary>  
        /// 传真号码  
        /// </summary>  
        public string sufaxno { get; set; } 
    
        /// <summary>  
        /// 行走路线  
        /// </summary>  
        public string suwalkaddr { get; set; } 
    
        /// <summary>  
        /// 备注  
        /// </summary>  
        public string sumemo { get; set; } 
    
        /// <summary>  
        /// 供应商id  
        /// </summary>  
        public Nullable<int> peoid { get; set; } 
    }
}
