//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class takeadvancegatherdetails
    {
    
        /// <summary>  
        /// 详表ID  
        /// </summary>  
        public string Takid { get; set; } 
    
        /// <summary>  
        /// 应付冲款单单号  
        /// </summary>  
        public string Payid { get; set; } 
    
        /// <summary>  
        /// 预收单单号  
        /// </summary>  
        public string Advid { get; set; } 
    
        /// <summary>  
        /// 预收单行号  
        /// </summary>  
        public string Advdetid { get; set; } 
    
        /// <summary>  
        /// 取用预收金额  
        /// </summary>  
        public float Takadvmoney { get; set; } 
    
        /// <summary>  
        /// 标识是否删除  
        /// </summary>  
        public int Enables { get; set; } 
    
        /// <summary>  
        /// 保留字段1  
        /// </summary>  
        public string Safetyone { get; set; } 
    
        /// <summary>  
        /// 保留字段2  
        /// </summary>  
        public string Safetytwo { get; set; } 
    
        /// <summary>  
        /// 扩展字段0  
        /// </summary>  
        public string Extend0 { get; set; } 
    
        /// <summary>  
        /// 扩展字段1  
        /// </summary>  
        public string Extend1 { get; set; } 
    
        /// <summary>  
        /// 扩展字段2  
        /// </summary>  
        public string Extend2 { get; set; } 
    
        /// <summary>  
        /// 扩展字段3  
        /// </summary>  
        public string Extend3 { get; set; } 
    
        /// <summary>  
        /// 扩展字段4  
        /// </summary>  
        public string Extend4 { get; set; } 
    }
}
